services:

  postgresql:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 2s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 3
    logging:
      driver: none

  ollama-setup:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: /bin/sh
    command: >
      -c "
      ollama pull gemma3:270m &&
      ollama pull nomic-embed-text:latest &&
      echo 'Models downloaded successfully'
      "
    logging:
      driver: none

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
      ollama-setup:
        condition: service_completed_successfully
    logging:
      driver: json-file

volumes:
  ollama_data:
  postgres_data: